linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - gosec
    - varcheck
#    - golint
    - goimports
  disable:
    - ineffassign
    - dupl
    - godox
    - bodyclose # too many false negatives

linters-settings:
  goimports:
    local-prefixes: github.com/ory

run:
  skip-dirs:
    - sdk/
  skip-files:
    - ".+_test.go"
    - "corpx/faker.go"
