linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - typecheck
    - unused
    - gosec
#    - golint
    - goimports
  disable:
    - ineffassign
    - dupl
    - godox
    - bodyclose # too many false negatives

linters-settings:
  goimports:
    local-prefixes: github.com/ory

issues:
  exclude-dirs:
    - sdk/
  exclude-files:
    - ".+_test.go"
    - "corpx/faker.go"
  exclude:
    - "Set is deprecated: use context-based WithConfigValue instead"
    - "SetDefaultIdentitySchemaFromRaw is deprecated: Use context-based WithDefaultIdentitySchemaFromRaw instead"
    - "SetDefaultIdentitySchema is deprecated: Use context-based WithDefaultIdentitySchema instead"
