version: 2

includes:
  - from_url:
      url: https://raw.githubusercontent.com/ory/xgoreleaser/acbadd5d1b947b046fdd0a534b132509eba8e3c8/build.tmpl.yml

variables:
  brew_name: kratos
  brew_description: "The Ory Identity Platform (Ory Kratos)"
  buildinfo_hash: "github.com/ory/kratos/driver/config.Commit"
  buildinfo_tag: "github.com/ory/kratos/driver/config.Version"
  buildinfo_date: "github.com/ory/kratos/driver/config.Date"
  dockerfile_alpine: ".docker/Dockerfile-alpine"
  dockerfile_static: ".docker/Dockerfile-distroless-static"

project_name: kratos

after:
  hooks:
  - cmd: "bash <(curl -s https://raw.githubusercontent.com/ory/xgoreleaser/master/docs.sh)"
    env:
      - "TAG_VERSION={{ .Tag }}"
      - "DOCS_VERSION={{ .Major }}.{{ .Minor }}"
