includes:
  - from_url:
      url: https://raw.githubusercontent.com/ory/xgoreleaser/master/build.tmpl.yml

variables:
  brew_name: kratos

  brew_description: "The Ory Kratos Identity Platform"

  buildinfo_hash: "github.com/ory/kratos/driver/config.Commit"
  buildinfo_tag: "github.com/ory/kratos/driver/config.Version"
  buildinfo_date: "github.com/ory/kratos/driver/config.Date"
  dockerfile: ".docker/Dockerfile"

project_name: kratos

after:
  hooks:
    - cmd: npm i
      dir: docs
    - cmd: |
        node "./docs/scripts/docker-tag.js" "docs/config.js" "{{.Tag}}"
    - cmd: |
        node "./docs/scripts/rerelease.js" "v{{ .Major }}{{ .Minor }}"
    - cmd: |
        rm -rf "./docs/versioned_docs/version-v{{ .Major }}{{ .Minor }}"
    - cmd: |
        rm -rf "./docs/versioned_sidebars/version-v{{ .Major }}{{ .Minor }}-sidebars.json"
    - cmd: |
        npm run docusaurus docs:version "v{{ .Major }}{{ .Minor }}"
      dir: docs
    - cmd: |
        npm run format
      dir: docs
