coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 10%
        only_pulls: true
ignore:
  - "test"
  - "internal"
  - "docs"
  - "contrib"
  - "selfservice/strategy/oidc/provider_netid.go" # No way to test this provider automatically
