DROP TABLE "selfservice_login_flow_methods";COMMIT TRANSACTION;BEGIN TRANSACTION;
ALTER TABLE "selfservice_login_flows" ADD COLUMN "ui" json;COMMIT TRANSACTION;BEGIN TRANSACTION;
ALTER TABLE "selfservice_login_flows" DROP COLUMN "messages";COMMIT TRANSACTION;BEGIN TRANSACTION;