CREATE INDEX identity_credential_identifiers_nid_id_idx ON identity_credential_identifiers (nid ASC, id ASC)
CREATE INDEX identity_credential_identifiers_id_nid_idx ON identity_credential_identifiers (id ASC, nid ASC)
CREATE INDEX identity_verifiable_addresses_status_via_idx ON ory_kratos.public.identity_verifiable_addresses USING btree (nid ASC, via ASC, value ASC)
CREATE INDEX identity_recovery_addresses_status_via_idx ON ory_kratos.public.identity_recovery_addresses USING btree (nid ASC, via ASC, value ASC)
CREATE INDEX session_devices_id_nid_idx ON ory_kratos.public.session_devices USING btree (id ASC, nid ASC)
CREATE INDEX courier_message_dispatches_id_message_id_nid_idx ON ory_kratos.public.courier_message_dispatches USING btree (id ASC, message_id ASC, nid ASC)
CREATE INDEX continuity_containers_id_nid_idx ON ory_kratos.public.continuity_containers USING btree (id ASC, nid ASC)
CREATE UNIQUE INDEX identity_verification_tokens_token_uq_idx ON ory_kratos.public.identity_verification_tokens USING btree (token ASC)
CREATE INDEX identity_verification_tokens_verification_flow_id_idx ON ory_kratos.public.identity_verification_tokens USING btree (selfservice_verification_flow_id ASC)
CREATE INDEX identity_verification_tokens_nid_id_idx ON ory_kratos.public.identity_verification_tokens USING btree (nid ASC, id ASC)
CREATE INDEX identity_verification_tokens_id_nid_idx ON ory_kratos.public.identity_verification_tokens USING btree (id ASC, nid ASC)
CREATE UNIQUE INDEX identity_recovery_addresses_code_uq_idx ON ory_kratos.public.identity_recovery_tokens USING btree (token ASC)
CREATE INDEX identity_recovery_tokens_id_nid_idx ON ory_kratos.public.identity_recovery_tokens USING btree (id ASC, nid ASC)
CREATE INDEX identity_login_codes_id_nid_idx ON ory_kratos.public.identity_login_codes USING btree (id ASC, nid ASC)
CREATE INDEX schema_migration_version_self_idx ON ory_kratos.public.schema_migration USING btree (version_self ASC)
CREATE UNIQUE INDEX schema_migration_version_idx ON ory_kratos.public.schema_migration USING btree (version ASC)
