- op: replace
  path: /info
  value:
    title: Ory Identities API
    description: |
      This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.
    version: >-
      {{ getenv "CIRCLE_TAG" }}
    license:
      name: Apache 2.0
    contact:
      email: "office@ory.sh"
- op: replace
  path: /tags
  value:
    - name: identity
      description: APIs for managing identities.
    - name: frontend
      description: Endpoints used by frontend applications (e.g. Single-Page-App, Native Apps, Server Apps, ...) to manage a user's own profile.
    - name: courier
      description: APIs for managing email and SMS message delivery.
    - name: metadata
      description: Server Metadata provides relevant information about the running server. Only available when self-hosting this service.
