# Makes uiNodeAttributes polymorph
- op: remove
  path: /components/schemas/uiNodeAttributes/type
- op: add
  path: /components/schemas/uiNodeAttributes/oneOf
  value:
    - "$ref": "#/components/schemas/uiNodeInputAttributes"
    - "$ref": "#/components/schemas/uiNodeTextAttributes"
    - "$ref": "#/components/schemas/uiNodeImageAttributes"
    - "$ref": "#/components/schemas/uiNodeAnchorAttributes"

# Makes the uiNodeInputAttributes value attribute polymorph
- op: remove
  path: /components/schemas/uiNodeInputAttributes/properties/value/type
- op: add
  path: /components/schemas/uiNodeInputAttributes/properties/value/nullable
  value: true

- op: replace
  path: /components/schemas/selfServiceError/properties/error
  value:
    type: object

- op: remove
  path: "#/components/schemas/identityTraits/type"
