# Makes uiNodeAttributes polymorph
- op: remove
  path: /components/schemas/uiNodeAttributes/type
- op: add
  path: /components/schemas/uiNodeAttributes/discriminator
  value:
    propertyName: node_type
    mapping:
      input: "#/components/schemas/uiNodeInputAttributes"
      text: "#/components/schemas/uiNodeTextAttributes"
      img: "#/components/schemas/uiNodeImageAttributes"
      a: "#/components/schemas/uiNodeAnchorAttributes"
      script: "#/components/schemas/uiNodeScriptAttributes"
      div: "#/components/schemas/uiNodeDivisionAttributes"
- op: add
  path: /components/schemas/uiNodeAttributes/oneOf
  value:
    - "$ref": "#/components/schemas/uiNodeInputAttributes"
    - "$ref": "#/components/schemas/uiNodeTextAttributes"
    - "$ref": "#/components/schemas/uiNodeImageAttributes"
    - "$ref": "#/components/schemas/uiNodeAnchorAttributes"
    - "$ref": "#/components/schemas/uiNodeScriptAttributes"
    - "$ref": "#/components/schemas/uiNodeDivisionAttributes"

# Makes the uiNodeInputAttributes value attribute polymorph
- op: add
  path: /components/schemas/uiNodeInputAttributes/properties/value/nullable
  value: true


- op: replace
  path: /components/schemas/flowError/properties/error
  value:
    type: object

- op: remove
  path: "#/components/schemas/identityTraits/type"

- op: add
  path: /components/schemas/continueWith/discriminator
  value:
    propertyName: action
    mapping:
      show_verification_ui: "#/components/schemas/continueWithVerificationUi"
      set_ory_session_token: "#/components/schemas/continueWithSetOrySessionToken"
      show_settings_ui: "#/components/schemas/continueWithSettingsUi"
      show_recovery_ui: "#/components/schemas/continueWithRecoveryUi"
      redirect_browser_to: "#/components/schemas/continueWithRedirectBrowserTo"

- op: add
  path: /components/schemas/continueWith/oneOf
  value:
    - "$ref": "#/components/schemas/continueWithVerificationUi"
    - "$ref": "#/components/schemas/continueWithSetOrySessionToken"
    - "$ref": "#/components/schemas/continueWithSettingsUi"
    - "$ref": "#/components/schemas/continueWithRecoveryUi"
    - "$ref": "#/components/schemas/continueWithRedirectBrowserTo"
