// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/kratos-client-go/models"
)

// CompleteSelfServiceSettingsFlowWithProfileMethodReader is a Reader for the CompleteSelfServiceSettingsFlowWithProfileMethod structure.
type CompleteSelfServiceSettingsFlowWithProfileMethodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompleteSelfServiceSettingsFlowWithProfileMethodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCompleteSelfServiceSettingsFlowWithProfileMethodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 302:
		result := NewCompleteSelfServiceSettingsFlowWithProfileMethodFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewCompleteSelfServiceSettingsFlowWithProfileMethodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCompleteSelfServiceSettingsFlowWithProfileMethodForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCompleteSelfServiceSettingsFlowWithProfileMethodOK creates a CompleteSelfServiceSettingsFlowWithProfileMethodOK with default headers values
func NewCompleteSelfServiceSettingsFlowWithProfileMethodOK() *CompleteSelfServiceSettingsFlowWithProfileMethodOK {
	return &CompleteSelfServiceSettingsFlowWithProfileMethodOK{}
}

/*CompleteSelfServiceSettingsFlowWithProfileMethodOK handles this case with default header values.

settingsFlow
*/
type CompleteSelfServiceSettingsFlowWithProfileMethodOK struct {
	Payload *models.SettingsFlow
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodOK) Error() string {
	return fmt.Sprintf("[POST /self-service/settings/methods/profile][%d] completeSelfServiceSettingsFlowWithProfileMethodOK  %+v", 200, o.Payload)
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodOK) GetPayload() *models.SettingsFlow {
	return o.Payload
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SettingsFlow)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompleteSelfServiceSettingsFlowWithProfileMethodFound creates a CompleteSelfServiceSettingsFlowWithProfileMethodFound with default headers values
func NewCompleteSelfServiceSettingsFlowWithProfileMethodFound() *CompleteSelfServiceSettingsFlowWithProfileMethodFound {
	return &CompleteSelfServiceSettingsFlowWithProfileMethodFound{}
}

/*CompleteSelfServiceSettingsFlowWithProfileMethodFound handles this case with default header values.

Empty responses are sent when, for example, resources are deleted. The HTTP status code for empty responses is
typically 201.
*/
type CompleteSelfServiceSettingsFlowWithProfileMethodFound struct {
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodFound) Error() string {
	return fmt.Sprintf("[POST /self-service/settings/methods/profile][%d] completeSelfServiceSettingsFlowWithProfileMethodFound ", 302)
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCompleteSelfServiceSettingsFlowWithProfileMethodBadRequest creates a CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest with default headers values
func NewCompleteSelfServiceSettingsFlowWithProfileMethodBadRequest() *CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest {
	return &CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest{}
}

/*CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest handles this case with default header values.

settingsFlow
*/
type CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest struct {
	Payload *models.SettingsFlow
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest) Error() string {
	return fmt.Sprintf("[POST /self-service/settings/methods/profile][%d] completeSelfServiceSettingsFlowWithProfileMethodBadRequest  %+v", 400, o.Payload)
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest) GetPayload() *models.SettingsFlow {
	return o.Payload
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SettingsFlow)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized creates a CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized with default headers values
func NewCompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized() *CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized {
	return &CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized{}
}

/*CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized handles this case with default header values.

genericError
*/
type CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized struct {
	Payload *models.GenericError
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized) Error() string {
	return fmt.Sprintf("[POST /self-service/settings/methods/profile][%d] completeSelfServiceSettingsFlowWithProfileMethodUnauthorized  %+v", 401, o.Payload)
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompleteSelfServiceSettingsFlowWithProfileMethodForbidden creates a CompleteSelfServiceSettingsFlowWithProfileMethodForbidden with default headers values
func NewCompleteSelfServiceSettingsFlowWithProfileMethodForbidden() *CompleteSelfServiceSettingsFlowWithProfileMethodForbidden {
	return &CompleteSelfServiceSettingsFlowWithProfileMethodForbidden{}
}

/*CompleteSelfServiceSettingsFlowWithProfileMethodForbidden handles this case with default header values.

genericError
*/
type CompleteSelfServiceSettingsFlowWithProfileMethodForbidden struct {
	Payload *models.GenericError
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodForbidden) Error() string {
	return fmt.Sprintf("[POST /self-service/settings/methods/profile][%d] completeSelfServiceSettingsFlowWithProfileMethodForbidden  %+v", 403, o.Payload)
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodForbidden) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError creates a CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError with default headers values
func NewCompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError() *CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError {
	return &CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError{}
}

/*CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError handles this case with default header values.

genericError
*/
type CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError struct {
	Payload *models.GenericError
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /self-service/settings/methods/profile][%d] completeSelfServiceSettingsFlowWithProfileMethodInternalServerError  %+v", 500, o.Payload)
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CompleteSelfServiceSettingsFlowWithProfileMethodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
