// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCompleteSelfServiceLoginFlowWithPasswordParams creates a new CompleteSelfServiceLoginFlowWithPasswordParams object
// with the default values initialized.
func NewCompleteSelfServiceLoginFlowWithPasswordParams() *CompleteSelfServiceLoginFlowWithPasswordParams {
	var ()
	return &CompleteSelfServiceLoginFlowWithPasswordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCompleteSelfServiceLoginFlowWithPasswordParamsWithTimeout creates a new CompleteSelfServiceLoginFlowWithPasswordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCompleteSelfServiceLoginFlowWithPasswordParamsWithTimeout(timeout time.Duration) *CompleteSelfServiceLoginFlowWithPasswordParams {
	var ()
	return &CompleteSelfServiceLoginFlowWithPasswordParams{

		timeout: timeout,
	}
}

// NewCompleteSelfServiceLoginFlowWithPasswordParamsWithContext creates a new CompleteSelfServiceLoginFlowWithPasswordParams object
// with the default values initialized, and the ability to set a context for a request
func NewCompleteSelfServiceLoginFlowWithPasswordParamsWithContext(ctx context.Context) *CompleteSelfServiceLoginFlowWithPasswordParams {
	var ()
	return &CompleteSelfServiceLoginFlowWithPasswordParams{

		Context: ctx,
	}
}

// NewCompleteSelfServiceLoginFlowWithPasswordParamsWithHTTPClient creates a new CompleteSelfServiceLoginFlowWithPasswordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCompleteSelfServiceLoginFlowWithPasswordParamsWithHTTPClient(client *http.Client) *CompleteSelfServiceLoginFlowWithPasswordParams {
	var ()
	return &CompleteSelfServiceLoginFlowWithPasswordParams{
		HTTPClient: client,
	}
}

/*CompleteSelfServiceLoginFlowWithPasswordParams contains all the parameters to send to the API endpoint
for the complete self service login flow with password operation typically these are written to a http.Request
*/
type CompleteSelfServiceLoginFlowWithPasswordParams struct {

	/*Identifier*/
	Identifier *string
	/*Password*/
	Password *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) WithTimeout(timeout time.Duration) *CompleteSelfServiceLoginFlowWithPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) WithContext(ctx context.Context) *CompleteSelfServiceLoginFlowWithPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) WithHTTPClient(client *http.Client) *CompleteSelfServiceLoginFlowWithPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIdentifier adds the identifier to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) WithIdentifier(identifier *string) *CompleteSelfServiceLoginFlowWithPasswordParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) SetIdentifier(identifier *string) {
	o.Identifier = identifier
}

// WithPassword adds the password to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) WithPassword(password *string) *CompleteSelfServiceLoginFlowWithPasswordParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the complete self service login flow with password params
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) SetPassword(password *string) {
	o.Password = password
}

// WriteToRequest writes these params to a swagger request
func (o *CompleteSelfServiceLoginFlowWithPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Identifier != nil {

		// query param identifier
		var qrIdentifier string
		if o.Identifier != nil {
			qrIdentifier = *o.Identifier
		}
		qIdentifier := qrIdentifier
		if qIdentifier != "" {
			if err := r.SetQueryParam("identifier", qIdentifier); err != nil {
				return err
			}
		}

	}

	if o.Password != nil {

		// query param password
		var qrPassword string
		if o.Password != nil {
			qrPassword = *o.Password
		}
		qPassword := qrPassword
		if qPassword != "" {
			if err := r.SetQueryParam("password", qPassword); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
