// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/kratos/internal/httpclient/models"
)

// CompleteSelfServiceLoginFlowWithPasswordReader is a Reader for the CompleteSelfServiceLoginFlowWithPassword structure.
type CompleteSelfServiceLoginFlowWithPasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompleteSelfServiceLoginFlowWithPasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCompleteSelfServiceLoginFlowWithPasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 302:
		result := NewCompleteSelfServiceLoginFlowWithPasswordFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewCompleteSelfServiceLoginFlowWithPasswordBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCompleteSelfServiceLoginFlowWithPasswordInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCompleteSelfServiceLoginFlowWithPasswordOK creates a CompleteSelfServiceLoginFlowWithPasswordOK with default headers values
func NewCompleteSelfServiceLoginFlowWithPasswordOK() *CompleteSelfServiceLoginFlowWithPasswordOK {
	return &CompleteSelfServiceLoginFlowWithPasswordOK{}
}

/*CompleteSelfServiceLoginFlowWithPasswordOK handles this case with default header values.

Login Flow for API Clients Response
*/
type CompleteSelfServiceLoginFlowWithPasswordOK struct {
	/*SessionToken

	A session token is equivalent to a session cookie, but it can be sent in the HTTP Authorization
	Header:

	Authorization: bearer <session-token>

	required: true
	*/
	SessionToken string
}

func (o *CompleteSelfServiceLoginFlowWithPasswordOK) Error() string {
	return fmt.Sprintf("[GET /self-service/browser/flows/login/strategies/password][%d] completeSelfServiceLoginFlowWithPasswordOK ", 200)
}

func (o *CompleteSelfServiceLoginFlowWithPasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header session_token
	o.SessionToken = response.GetHeader("session_token")

	return nil
}

// NewCompleteSelfServiceLoginFlowWithPasswordFound creates a CompleteSelfServiceLoginFlowWithPasswordFound with default headers values
func NewCompleteSelfServiceLoginFlowWithPasswordFound() *CompleteSelfServiceLoginFlowWithPasswordFound {
	return &CompleteSelfServiceLoginFlowWithPasswordFound{}
}

/*CompleteSelfServiceLoginFlowWithPasswordFound handles this case with default header values.

Empty responses are sent when, for example, resources are deleted. The HTTP status code for empty responses is
typically 201.
*/
type CompleteSelfServiceLoginFlowWithPasswordFound struct {
}

func (o *CompleteSelfServiceLoginFlowWithPasswordFound) Error() string {
	return fmt.Sprintf("[GET /self-service/browser/flows/login/strategies/password][%d] completeSelfServiceLoginFlowWithPasswordFound ", 302)
}

func (o *CompleteSelfServiceLoginFlowWithPasswordFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCompleteSelfServiceLoginFlowWithPasswordBadRequest creates a CompleteSelfServiceLoginFlowWithPasswordBadRequest with default headers values
func NewCompleteSelfServiceLoginFlowWithPasswordBadRequest() *CompleteSelfServiceLoginFlowWithPasswordBadRequest {
	return &CompleteSelfServiceLoginFlowWithPasswordBadRequest{}
}

/*CompleteSelfServiceLoginFlowWithPasswordBadRequest handles this case with default header values.

genericError
*/
type CompleteSelfServiceLoginFlowWithPasswordBadRequest struct {
	Payload *models.GenericError
}

func (o *CompleteSelfServiceLoginFlowWithPasswordBadRequest) Error() string {
	return fmt.Sprintf("[GET /self-service/browser/flows/login/strategies/password][%d] completeSelfServiceLoginFlowWithPasswordBadRequest  %+v", 400, o.Payload)
}

func (o *CompleteSelfServiceLoginFlowWithPasswordBadRequest) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CompleteSelfServiceLoginFlowWithPasswordBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompleteSelfServiceLoginFlowWithPasswordInternalServerError creates a CompleteSelfServiceLoginFlowWithPasswordInternalServerError with default headers values
func NewCompleteSelfServiceLoginFlowWithPasswordInternalServerError() *CompleteSelfServiceLoginFlowWithPasswordInternalServerError {
	return &CompleteSelfServiceLoginFlowWithPasswordInternalServerError{}
}

/*CompleteSelfServiceLoginFlowWithPasswordInternalServerError handles this case with default header values.

genericError
*/
type CompleteSelfServiceLoginFlowWithPasswordInternalServerError struct {
	Payload *models.GenericError
}

func (o *CompleteSelfServiceLoginFlowWithPasswordInternalServerError) Error() string {
	return fmt.Sprintf("[GET /self-service/browser/flows/login/strategies/password][%d] completeSelfServiceLoginFlowWithPasswordInternalServerError  %+v", 500, o.Payload)
}

func (o *CompleteSelfServiceLoginFlowWithPasswordInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CompleteSelfServiceLoginFlowWithPasswordInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
