// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/kratos-client-go/models"
)

// CompleteSelfServiceVerificationFlowWithLinkMethodReader is a Reader for the CompleteSelfServiceVerificationFlowWithLinkMethod structure.
type CompleteSelfServiceVerificationFlowWithLinkMethodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompleteSelfServiceVerificationFlowWithLinkMethodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 302:
		result := NewCompleteSelfServiceVerificationFlowWithLinkMethodFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewCompleteSelfServiceVerificationFlowWithLinkMethodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCompleteSelfServiceVerificationFlowWithLinkMethodFound creates a CompleteSelfServiceVerificationFlowWithLinkMethodFound with default headers values
func NewCompleteSelfServiceVerificationFlowWithLinkMethodFound() *CompleteSelfServiceVerificationFlowWithLinkMethodFound {
	return &CompleteSelfServiceVerificationFlowWithLinkMethodFound{}
}

/*CompleteSelfServiceVerificationFlowWithLinkMethodFound handles this case with default header values.

Empty responses are sent when, for example, resources are deleted. The HTTP status code for empty responses is
typically 201.
*/
type CompleteSelfServiceVerificationFlowWithLinkMethodFound struct {
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodFound) Error() string {
	return fmt.Sprintf("[POST /self-service/verification/methods/link][%d] completeSelfServiceVerificationFlowWithLinkMethodFound ", 302)
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCompleteSelfServiceVerificationFlowWithLinkMethodBadRequest creates a CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest with default headers values
func NewCompleteSelfServiceVerificationFlowWithLinkMethodBadRequest() *CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest {
	return &CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest{}
}

/*CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest handles this case with default header values.

verificationFlow
*/
type CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest struct {
	Payload *models.VerificationFlow
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest) Error() string {
	return fmt.Sprintf("[POST /self-service/verification/methods/link][%d] completeSelfServiceVerificationFlowWithLinkMethodBadRequest  %+v", 400, o.Payload)
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest) GetPayload() *models.VerificationFlow {
	return o.Payload
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VerificationFlow)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError creates a CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError with default headers values
func NewCompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError() *CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError {
	return &CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError{}
}

/*CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError handles this case with default header values.

genericError
*/
type CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError struct {
	Payload *models.GenericError
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /self-service/verification/methods/link][%d] completeSelfServiceVerificationFlowWithLinkMethodInternalServerError  %+v", 500, o.Payload)
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CompleteSelfServiceVerificationFlowWithLinkMethodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
