// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInitializeProfileManagementFlowParams creates a new InitializeProfileManagementFlowParams object
// with the default values initialized.
func NewInitializeProfileManagementFlowParams() *InitializeProfileManagementFlowParams {

	return &InitializeProfileManagementFlowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInitializeProfileManagementFlowParamsWithTimeout creates a new InitializeProfileManagementFlowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInitializeProfileManagementFlowParamsWithTimeout(timeout time.Duration) *InitializeProfileManagementFlowParams {

	return &InitializeProfileManagementFlowParams{

		timeout: timeout,
	}
}

// NewInitializeProfileManagementFlowParamsWithContext creates a new InitializeProfileManagementFlowParams object
// with the default values initialized, and the ability to set a context for a request
func NewInitializeProfileManagementFlowParamsWithContext(ctx context.Context) *InitializeProfileManagementFlowParams {

	return &InitializeProfileManagementFlowParams{

		Context: ctx,
	}
}

// NewInitializeProfileManagementFlowParamsWithHTTPClient creates a new InitializeProfileManagementFlowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInitializeProfileManagementFlowParamsWithHTTPClient(client *http.Client) *InitializeProfileManagementFlowParams {

	return &InitializeProfileManagementFlowParams{
		HTTPClient: client,
	}
}

/*InitializeProfileManagementFlowParams contains all the parameters to send to the API endpoint
for the initialize profile management flow operation typically these are written to a http.Request
*/
type InitializeProfileManagementFlowParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the initialize profile management flow params
func (o *InitializeProfileManagementFlowParams) WithTimeout(timeout time.Duration) *InitializeProfileManagementFlowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the initialize profile management flow params
func (o *InitializeProfileManagementFlowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the initialize profile management flow params
func (o *InitializeProfileManagementFlowParams) WithContext(ctx context.Context) *InitializeProfileManagementFlowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the initialize profile management flow params
func (o *InitializeProfileManagementFlowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the initialize profile management flow params
func (o *InitializeProfileManagementFlowParams) WithHTTPClient(client *http.Client) *InitializeProfileManagementFlowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the initialize profile management flow params
func (o *InitializeProfileManagementFlowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *InitializeProfileManagementFlowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
