/*
Ory Identities API

This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.

API version:
Contact: office@ory.sh
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the IdentityCredentialsWebAuthnAttestation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityCredentialsWebAuthnAttestation{}

// IdentityCredentialsWebAuthnAttestation struct for IdentityCredentialsWebAuthnAttestation
type IdentityCredentialsWebAuthnAttestation struct {
	AuthenticatorData    []int32 `json:"authenticator_data,omitempty"`
	ClientDataJSON       []int32 `json:"client_dataJSON,omitempty"`
	ClientDataHash       []int32 `json:"client_data_hash,omitempty"`
	Object               []int32 `json:"object,omitempty"`
	PublicKeyAlgorithm   *int64  `json:"public_key_algorithm,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdentityCredentialsWebAuthnAttestation IdentityCredentialsWebAuthnAttestation

// NewIdentityCredentialsWebAuthnAttestation instantiates a new IdentityCredentialsWebAuthnAttestation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityCredentialsWebAuthnAttestation() *IdentityCredentialsWebAuthnAttestation {
	this := IdentityCredentialsWebAuthnAttestation{}
	return &this
}

// NewIdentityCredentialsWebAuthnAttestationWithDefaults instantiates a new IdentityCredentialsWebAuthnAttestation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityCredentialsWebAuthnAttestationWithDefaults() *IdentityCredentialsWebAuthnAttestation {
	this := IdentityCredentialsWebAuthnAttestation{}
	return &this
}

// GetAuthenticatorData returns the AuthenticatorData field value if set, zero value otherwise.
func (o *IdentityCredentialsWebAuthnAttestation) GetAuthenticatorData() []int32 {
	if o == nil || IsNil(o.AuthenticatorData) {
		var ret []int32
		return ret
	}
	return o.AuthenticatorData
}

// GetAuthenticatorDataOk returns a tuple with the AuthenticatorData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityCredentialsWebAuthnAttestation) GetAuthenticatorDataOk() ([]int32, bool) {
	if o == nil || IsNil(o.AuthenticatorData) {
		return nil, false
	}
	return o.AuthenticatorData, true
}

// HasAuthenticatorData returns a boolean if a field has been set.
func (o *IdentityCredentialsWebAuthnAttestation) HasAuthenticatorData() bool {
	if o != nil && !IsNil(o.AuthenticatorData) {
		return true
	}

	return false
}

// SetAuthenticatorData gets a reference to the given []int32 and assigns it to the AuthenticatorData field.
func (o *IdentityCredentialsWebAuthnAttestation) SetAuthenticatorData(v []int32) {
	o.AuthenticatorData = v
}

// GetClientDataJSON returns the ClientDataJSON field value if set, zero value otherwise.
func (o *IdentityCredentialsWebAuthnAttestation) GetClientDataJSON() []int32 {
	if o == nil || IsNil(o.ClientDataJSON) {
		var ret []int32
		return ret
	}
	return o.ClientDataJSON
}

// GetClientDataJSONOk returns a tuple with the ClientDataJSON field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityCredentialsWebAuthnAttestation) GetClientDataJSONOk() ([]int32, bool) {
	if o == nil || IsNil(o.ClientDataJSON) {
		return nil, false
	}
	return o.ClientDataJSON, true
}

// HasClientDataJSON returns a boolean if a field has been set.
func (o *IdentityCredentialsWebAuthnAttestation) HasClientDataJSON() bool {
	if o != nil && !IsNil(o.ClientDataJSON) {
		return true
	}

	return false
}

// SetClientDataJSON gets a reference to the given []int32 and assigns it to the ClientDataJSON field.
func (o *IdentityCredentialsWebAuthnAttestation) SetClientDataJSON(v []int32) {
	o.ClientDataJSON = v
}

// GetClientDataHash returns the ClientDataHash field value if set, zero value otherwise.
func (o *IdentityCredentialsWebAuthnAttestation) GetClientDataHash() []int32 {
	if o == nil || IsNil(o.ClientDataHash) {
		var ret []int32
		return ret
	}
	return o.ClientDataHash
}

// GetClientDataHashOk returns a tuple with the ClientDataHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityCredentialsWebAuthnAttestation) GetClientDataHashOk() ([]int32, bool) {
	if o == nil || IsNil(o.ClientDataHash) {
		return nil, false
	}
	return o.ClientDataHash, true
}

// HasClientDataHash returns a boolean if a field has been set.
func (o *IdentityCredentialsWebAuthnAttestation) HasClientDataHash() bool {
	if o != nil && !IsNil(o.ClientDataHash) {
		return true
	}

	return false
}

// SetClientDataHash gets a reference to the given []int32 and assigns it to the ClientDataHash field.
func (o *IdentityCredentialsWebAuthnAttestation) SetClientDataHash(v []int32) {
	o.ClientDataHash = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *IdentityCredentialsWebAuthnAttestation) GetObject() []int32 {
	if o == nil || IsNil(o.Object) {
		var ret []int32
		return ret
	}
	return o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityCredentialsWebAuthnAttestation) GetObjectOk() ([]int32, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *IdentityCredentialsWebAuthnAttestation) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given []int32 and assigns it to the Object field.
func (o *IdentityCredentialsWebAuthnAttestation) SetObject(v []int32) {
	o.Object = v
}

// GetPublicKeyAlgorithm returns the PublicKeyAlgorithm field value if set, zero value otherwise.
func (o *IdentityCredentialsWebAuthnAttestation) GetPublicKeyAlgorithm() int64 {
	if o == nil || IsNil(o.PublicKeyAlgorithm) {
		var ret int64
		return ret
	}
	return *o.PublicKeyAlgorithm
}

// GetPublicKeyAlgorithmOk returns a tuple with the PublicKeyAlgorithm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityCredentialsWebAuthnAttestation) GetPublicKeyAlgorithmOk() (*int64, bool) {
	if o == nil || IsNil(o.PublicKeyAlgorithm) {
		return nil, false
	}
	return o.PublicKeyAlgorithm, true
}

// HasPublicKeyAlgorithm returns a boolean if a field has been set.
func (o *IdentityCredentialsWebAuthnAttestation) HasPublicKeyAlgorithm() bool {
	if o != nil && !IsNil(o.PublicKeyAlgorithm) {
		return true
	}

	return false
}

// SetPublicKeyAlgorithm gets a reference to the given int64 and assigns it to the PublicKeyAlgorithm field.
func (o *IdentityCredentialsWebAuthnAttestation) SetPublicKeyAlgorithm(v int64) {
	o.PublicKeyAlgorithm = &v
}

func (o IdentityCredentialsWebAuthnAttestation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityCredentialsWebAuthnAttestation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthenticatorData) {
		toSerialize["authenticator_data"] = o.AuthenticatorData
	}
	if !IsNil(o.ClientDataJSON) {
		toSerialize["client_dataJSON"] = o.ClientDataJSON
	}
	if !IsNil(o.ClientDataHash) {
		toSerialize["client_data_hash"] = o.ClientDataHash
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.PublicKeyAlgorithm) {
		toSerialize["public_key_algorithm"] = o.PublicKeyAlgorithm
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdentityCredentialsWebAuthnAttestation) UnmarshalJSON(data []byte) (err error) {
	varIdentityCredentialsWebAuthnAttestation := _IdentityCredentialsWebAuthnAttestation{}

	err = json.Unmarshal(data, &varIdentityCredentialsWebAuthnAttestation)

	if err != nil {
		return err
	}

	*o = IdentityCredentialsWebAuthnAttestation(varIdentityCredentialsWebAuthnAttestation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authenticator_data")
		delete(additionalProperties, "client_dataJSON")
		delete(additionalProperties, "client_data_hash")
		delete(additionalProperties, "object")
		delete(additionalProperties, "public_key_algorithm")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdentityCredentialsWebAuthnAttestation struct {
	value *IdentityCredentialsWebAuthnAttestation
	isSet bool
}

func (v NullableIdentityCredentialsWebAuthnAttestation) Get() *IdentityCredentialsWebAuthnAttestation {
	return v.value
}

func (v *NullableIdentityCredentialsWebAuthnAttestation) Set(val *IdentityCredentialsWebAuthnAttestation) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityCredentialsWebAuthnAttestation) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityCredentialsWebAuthnAttestation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityCredentialsWebAuthnAttestation(val *IdentityCredentialsWebAuthnAttestation) *NullableIdentityCredentialsWebAuthnAttestation {
	return &NullableIdentityCredentialsWebAuthnAttestation{value: val, isSet: true}
}

func (v NullableIdentityCredentialsWebAuthnAttestation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityCredentialsWebAuthnAttestation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
