courier:
  smtp:
    connection_uri: smtp://username:password@smtp.example.com:587
  channels:
    - id: phone
      request_config:
        url: https://ory.sh
        method: GET
        body: base64://ZnVuY3Rpb24oY3R4KSB7CkJvZHk6IGN0eC5ib2R5LApUbzogY3R4LnRvLEZyb206IGN0eC5mcm9tCn0=
        headers:
          Content-Type: application/x-www-form-urlencoded
        auth:
          type: basic_auth
          config:
            user: ABC
            password: DEF
