FROM oryd/xgoreleaser:1.14

WORKDIR /home/ory

ADD go.mod go.mod
ADD go.sum go.sum

RUN go mod download

ENV RELEASE_NAME=v0.0.0-alpha.1
ENV DOCKER_SHORT_TAG=v0.0.0-alpha.1

ADD . .
ENTRYPOINT ["goreleaser"]
CMD ["--snapshot", "--skip-publish", "--rm-dist"]

# Manual for debugging:
#   docker rm -f build || true; docker build -f .docker/Dockerfile-goreleaser -t build .; docker run build
#
# or:
#   docker rm -f build || true; docker build -f .docker/Dockerfile-goreleaser -t build .; docker run --cpus 6 --name build --entrypoint /bin/bash -it build
#   goreleaser --snapshot --skip-publish --rm-dist
