# serve controls the configuration for the http(s) daemon
serve:
  admin:
    base_url: http://admin.kratos.ory.sh
    port: 1234
    host: admin.kratos.ory.sh
  public:
    base_url: http://public.kratos.ory.sh
    port: 1235
    host: public.kratos.ory.sh

dsn: sqlite://foo.db?mode=memory&_fk=true

log:
  level: debug

courier:
  smtp:
    connection_uri: smtp://foo:bar@baz/

identity:
  default_schema_url: http://test.kratos.ory.sh/default-identity.schema.json
  schemas:
    - id: other
      url: http://test.kratos.ory.sh/other-identity.schema.json

hashers:
  argon2:
    memory: 1048576
    iterations: 2
    parallelism: 4
    salt_length: 16
    key_length: 32

secrets:
  cookie:
    - session-key-7f8a9b77-1
    - session-key-7f8a9b77-2

selfservice:
  default_browser_return_url: http://return-to-3-test.ory.sh/
  whitelisted_return_urls:
    - http://return-to-1-test.ory.sh/
    - http://return-to-2-test.ory.sh/
  strategies:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: a
            client_secret: b
            mapper_url: http://test.kratos.ory.sh/default-identity.schema.json
  flows:
    error:
      ui_url: http://test.kratos.ory.sh/error

    logout:
      after:
        default_browser_return_url: http://test.kratos.ory.sh:4000/

    recovery:
      enabled: true
      ui_url: http://test.kratos.ory.sh/recovery
      request_lifespan: 98m
      after:
        default_browser_return_url: http://test.kratos.ory.sh/dashboard

    verification:
      enabled: true
      request_lifespan: 97m
      ui_url: http://test.kratos.ory.sh/verification
      after:
        default_browser_return_url: http://test.kratos.ory.sh/dashboard

    settings:
      ui_url:  http://test.kratos.ory.sh/settings
      request_lifespan: 99m
      privileged_session_max_age: 5m
      after:
        default_browser_return_url: https://self-service/settings/return_to
        password:
          default_browser_return_url: https://self-service/settings/password/return_to
    login:
      ui_url: http://test.kratos.ory.sh/login
      request_lifespan: 99m
      after:
        default_browser_return_url: https://self-service/login/return_to
        password:
          default_browser_return_url: https://self-service/login/password/return_to
          hooks:
            -
              hook: revoke_active_sessions
        oidc:
          hooks:
            -
              hook: revoke_active_sessions
    registration:
      ui_url: http://test.kratos.ory.sh/register
      request_lifespan: 98m
      after:
        default_browser_return_url: https://self-service/registration/return_to
        password:
          hooks:
            -
              hook: session
        oidc:
          default_browser_return_url: https://self-service/registration/oidc/return_to
          hooks:
            -
              hook: session
