// Code generated by go-swagger; DO NOT EDIT.

package common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSelfServiceBrowserProfileManagementRequestParams creates a new GetSelfServiceBrowserProfileManagementRequestParams object
// with the default values initialized.
func NewGetSelfServiceBrowserProfileManagementRequestParams() *GetSelfServiceBrowserProfileManagementRequestParams {
	var ()
	return &GetSelfServiceBrowserProfileManagementRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSelfServiceBrowserProfileManagementRequestParamsWithTimeout creates a new GetSelfServiceBrowserProfileManagementRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSelfServiceBrowserProfileManagementRequestParamsWithTimeout(timeout time.Duration) *GetSelfServiceBrowserProfileManagementRequestParams {
	var ()
	return &GetSelfServiceBrowserProfileManagementRequestParams{

		timeout: timeout,
	}
}

// NewGetSelfServiceBrowserProfileManagementRequestParamsWithContext creates a new GetSelfServiceBrowserProfileManagementRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSelfServiceBrowserProfileManagementRequestParamsWithContext(ctx context.Context) *GetSelfServiceBrowserProfileManagementRequestParams {
	var ()
	return &GetSelfServiceBrowserProfileManagementRequestParams{

		Context: ctx,
	}
}

// NewGetSelfServiceBrowserProfileManagementRequestParamsWithHTTPClient creates a new GetSelfServiceBrowserProfileManagementRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSelfServiceBrowserProfileManagementRequestParamsWithHTTPClient(client *http.Client) *GetSelfServiceBrowserProfileManagementRequestParams {
	var ()
	return &GetSelfServiceBrowserProfileManagementRequestParams{
		HTTPClient: client,
	}
}

/*GetSelfServiceBrowserProfileManagementRequestParams contains all the parameters to send to the API endpoint
for the get self service browser profile management request operation typically these are written to a http.Request
*/
type GetSelfServiceBrowserProfileManagementRequestParams struct {

	/*Request
	  Request is the Login Request ID

	The value for this parameter comes from `request` URL Query parameter sent to your
	application (e.g. `/login?request=abcde`).

	*/
	Request string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) WithTimeout(timeout time.Duration) *GetSelfServiceBrowserProfileManagementRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) WithContext(ctx context.Context) *GetSelfServiceBrowserProfileManagementRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) WithHTTPClient(client *http.Client) *GetSelfServiceBrowserProfileManagementRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) WithRequest(request string) *GetSelfServiceBrowserProfileManagementRequestParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the get self service browser profile management request params
func (o *GetSelfServiceBrowserProfileManagementRequestParams) SetRequest(request string) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *GetSelfServiceBrowserProfileManagementRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param request
	qrRequest := o.Request
	qRequest := qrRequest
	if qRequest != "" {
		if err := r.SetQueryParam("request", qRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
