// Code generated by go-swagger; DO NOT EDIT.

package common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSelfServiceErrorParams creates a new GetSelfServiceErrorParams object
// with the default values initialized.
func NewGetSelfServiceErrorParams() *GetSelfServiceErrorParams {
	var ()
	return &GetSelfServiceErrorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSelfServiceErrorParamsWithTimeout creates a new GetSelfServiceErrorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSelfServiceErrorParamsWithTimeout(timeout time.Duration) *GetSelfServiceErrorParams {
	var ()
	return &GetSelfServiceErrorParams{

		timeout: timeout,
	}
}

// NewGetSelfServiceErrorParamsWithContext creates a new GetSelfServiceErrorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSelfServiceErrorParamsWithContext(ctx context.Context) *GetSelfServiceErrorParams {
	var ()
	return &GetSelfServiceErrorParams{

		Context: ctx,
	}
}

// NewGetSelfServiceErrorParamsWithHTTPClient creates a new GetSelfServiceErrorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSelfServiceErrorParamsWithHTTPClient(client *http.Client) *GetSelfServiceErrorParams {
	var ()
	return &GetSelfServiceErrorParams{
		HTTPClient: client,
	}
}

/*GetSelfServiceErrorParams contains all the parameters to send to the API endpoint
for the get self service error operation typically these are written to a http.Request
*/
type GetSelfServiceErrorParams struct {

	/*ID*/
	ID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get self service error params
func (o *GetSelfServiceErrorParams) WithTimeout(timeout time.Duration) *GetSelfServiceErrorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get self service error params
func (o *GetSelfServiceErrorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get self service error params
func (o *GetSelfServiceErrorParams) WithContext(ctx context.Context) *GetSelfServiceErrorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get self service error params
func (o *GetSelfServiceErrorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get self service error params
func (o *GetSelfServiceErrorParams) WithHTTPClient(client *http.Client) *GetSelfServiceErrorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get self service error params
func (o *GetSelfServiceErrorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get self service error params
func (o *GetSelfServiceErrorParams) WithID(id *string) *GetSelfServiceErrorParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get self service error params
func (o *GetSelfServiceErrorParams) SetID(id *string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSelfServiceErrorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
