// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Type type
//
// swagger:model Type
type Type string

// Validate validates this type
func (m Type) Validate(formats strfmt.Registry) error {
	return nil
}
