name: Codeball
on: [pull_request]

jobs:
  codeball_job:
    runs-on: ubuntu-latest
    name: Run Codeball
    steps:
      - name: Codeball AI Actions
        uses: sturdy-dev/codeball-action@v1
        # with:
        #   do-label: "true"                    # Configure if the action should label approved contributions
        #   label-name: "codeball:approved"     # Configure the label name to set if Codeball approves the contribution
        #   do-approve: "true"                  # Configure if the action should approve PRs that have been approved by Codeball
